[shellfirm]
src.github_tag = "kaplanelad/shellfirm"
src.from_pattern = "^(v([0-9\\.]+))$"
src.to_pattern = "\\1"
fetch.github = "kaplanelad/shellfirm"

[kratos]
src.github_tag = "go-kratos/kratos"
src.from_pattern = "^(([0-9\\.]+))$"
src.to_pattern = "\\1"
fetch.github = "go-kratos/kratos"

[goctl]
src.github_tag = "zeromicro/go-zero"
src.from_pattern = "^(v([0-9\\.]+))$"
src.to_pattern = "\\1"
fetch.github = "zeromicro/go-zero"

[1password-cli-linux]
src.manual = "v2.30.3"
fetch.tarball = "https://cache.agilebits.com/dist/1P/op2/pkg/$ver/op_linux_amd64_$ver.zip"

[dotnet-script]
src.github_tag = "dotnet-script/dotnet-script"
src.from_pattern = "^(([0-9\\.]+))$"
src.to_pattern = "\\1"
fetch.tarball = "https://github.com/dotnet-script/dotnet-script/releases/download/$ver/dotnet-script.$ver.zip"

[microsoft-edge]
src.aur = "microsoft-edge-stable-bin"
fetch.url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_$ver-1_amd64.deb"

[vscode-extension-kotlin-lsp]
src.github_tag = "Kotlin/kotlin-lsp"
src.include_regex = "kotlin-lsp/v.+"
src.from_pattern = "^kotlin-lsp/v(0.+)$"
src.to_pattern = "\\1"
fetch.url = "https://download-cdn.jetbrains.com/kotlin-lsp/$ver/kotlin-$ver.vsix"
url.name = "kotlin-lsp-$ver.zip"

[pwndbg]
src.github_tag = "pwndbg/pwndbg"
src.from_pattern = "^(\\d\\d\\d\\d\\.\\d\\d\\.\\d\\d)$"
src.to_pattern = "\\1"
fetch.github = "pwndbg/pwndbg"

[nix-vscode-extensions]
src.manual = "master"
fetch.github = "nix-community/nix-vscode-extensions"

[lix]
src.github_tag = "lix-project/lix"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.github = "lix-project/lix"

[devenv]
src.manual = "latest"
fetch.github = "cachix/devenv"

[python]
src.manual = "main"
fetch.github = "cachix/nixpkgs-python"

[font-firacode]
src.github_tag = "tonsky/FiraCode"
src.include_regex = "\\d+\\.\\d+"
fetch.url = "https://github.com/tonsky/FiraCode/releases/download/$ver/Fira_Code_v$ver.zip"
