# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  "1password-cli-linux" = {
    pname = "1password-cli-linux";
    version = "2.32.0";
    src = fetchTarball {
      url = "https://cache.agilebits.com/dist/1P/op2/pkg/v2.32.0/op_linux_amd64_v2.32.0.zip";
      sha256 = "sha256-4I7lSey6I4mQ7dDtuOASnZzAItFYkIDZ8UMsqb0q5tE=";
    };
  };
  deploy-rs = {
    pname = "deploy-rs";
    version = "125ae9e3ecf62fb2c0fd4f2d894eb971f1ecaed2";
    src = fetchFromGitHub {
      owner = "serokell";
      repo = "deploy-rs";
      rev = "125ae9e3ecf62fb2c0fd4f2d894eb971f1ecaed2";
      fetchSubmodules = false;
      sha256 = "sha256-N9gBKUmjwRKPxAafXEk1EGadfk2qDZPBQp4vXWPHINQ=";
    };
    date = "2025-09-01";
  };
  devenv = {
    pname = "devenv";
    version = "v1.10";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "devenv";
      rev = "v1.10";
      fetchSubmodules = false;
      sha256 = "sha256-rsb+6Wca43guzLL4Czoc89L394ZW9JZF2MShxaz2Sx4=";
    };
  };
  dotnet-script = {
    pname = "dotnet-script";
    version = "1.6.0";
    src = fetchTarball {
      url = "https://github.com/dotnet-script/dotnet-script/releases/download/1.6.0/dotnet-script.1.6.0.zip";
      sha256 = "sha256-Pc8+hja4OUajMLCOlieVLLvRMj74+OmecYlv3YyOvwo=";
    };
  };
  doxx = {
    pname = "doxx";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "bgreenwell";
      repo = "doxx";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-EFza7BSO0vBeUWWKNRnINSq/IUl8jLFUHKMfntdksdA=";
    };
  };
  font-firacode = {
    pname = "font-firacode";
    version = "6.2";
    src = fetchurl {
      url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip";
      sha256 = "sha256-CUmRW6jrJNif2T0Qp/9iP0KDDXxf/D7L+WDk7K0+Pnk=";
    };
  };
  goctl = {
    pname = "goctl";
    version = "v1.9.2";
    src = fetchFromGitHub {
      owner = "zeromicro";
      repo = "go-zero";
      rev = "v1.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-wS8Hb0sqP2iPjF3EgkmmsE6aHpyiRw4kcYpDPmJvpic=";
    };
  };
  kratos = {
    pname = "kratos";
    version = "v2.9.1";
    src = fetchFromGitHub {
      owner = "go-kratos";
      repo = "kratos";
      rev = "v2.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-fgYhrUNivtXNjSGCGCvG35PuKtQ/U5kyC2Irl2h8zXQ=";
    };
  };
  lix = {
    pname = "lix";
    version = "2.93.3";
    src = fetchFromGitHub {
      owner = "lix-project";
      repo = "lix";
      rev = "2.93.3";
      fetchSubmodules = false;
      sha256 = "sha256-Oqw04eboDM8rrUgAXiT7w5F2uGrQdt8sGX+Mk6mVXZQ=";
    };
  };
  microsoft-edge = {
    pname = "microsoft-edge";
    version = "141.0.3537.71";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_141.0.3537.71-1_amd64.deb";
      sha256 = "sha256-+R7c6xMBpmpVxUkr9Q9ewIGbGY8z5ZRe422sxouPzfI=";
    };
  };
  nix-vscode-extensions = {
    pname = "nix-vscode-extensions";
    version = "328cedcf3eae1e3eae4f16a61196894c95783c38";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nix-vscode-extensions";
      rev = "328cedcf3eae1e3eae4f16a61196894c95783c38";
      fetchSubmodules = false;
      sha256 = "sha256-Z8AXNGOME4FgNL54qqta7SU5O21oS7UjtcFaPyCHbHY=";
    };
    date = "2025-10-12";
  };
  pwndbg = {
    pname = "pwndbg";
    version = "2025.10.10";
    src = fetchFromGitHub {
      owner = "pwndbg";
      repo = "pwndbg";
      rev = "2025.10.10";
      fetchSubmodules = false;
      sha256 = "sha256-rQnUM/R2MuxVULvEzvQsdmjunN8opcZSvpGqwEy8G44=";
    };
  };
  python = {
    pname = "python";
    version = "5dd936b1ce299f6d230774a88b1052e47f71ab91";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "nixpkgs-python";
      rev = "5dd936b1ce299f6d230774a88b1052e47f71ab91";
      fetchSubmodules = false;
      sha256 = "sha256-BN4nmQIKBwYQzmASIMRu1RIIsztrF2ujb24yLTHFqFo=";
    };
    date = "2025-10-09";
  };
  shellfirm = {
    pname = "shellfirm";
    version = "v0.2.11";
    src = fetchFromGitHub {
      owner = "kaplanelad";
      repo = "shellfirm";
      rev = "v0.2.11";
      fetchSubmodules = false;
      sha256 = "sha256-jwrH2/EwiB33YoTC+pGO4Jm3tC4dp1DLZLZvhKvUy30=";
    };
  };
  trzsz = {
    pname = "trzsz";
    version = "v1.1.8";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-g1fbgKTFS9aPAmnTeFYoymrDEoZ6BtzUhA2Z9SNYbsU=";
    };
  };
  trzsz-ssh = {
    pname = "trzsz-ssh";
    version = "v0.1.22";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-ssh";
      rev = "v0.1.22";
      fetchSubmodules = false;
      sha256 = "sha256-VvPdWRP+lrhho+Bk5rT9pktEvKe01512WoDfAu5d868=";
    };
  };
  vscode-extension-kotlin-lsp = {
    pname = "vscode-extension-kotlin-lsp";
    version = "0.253.10629";
    src = fetchurl {
      url = "https://download-cdn.jetbrains.com/kotlin-lsp/0.253.10629/kotlin-0.253.10629.vsix";
      name = "kotlin-lsp-0.253.10629.zip";
      sha256 = "sha256-Y47BVS/eflFY+MffBkQ8+5fFwJlXJzeQWGy9WRFb8Rw=";
    };
  };
}
