# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  "1password-cli-linux" = {
    pname = "1password-cli-linux";
    version = "2.32.0";
    src = fetchTarball {
      url = "https://cache.agilebits.com/dist/1P/op2/pkg/v2.32.0/op_linux_amd64_v2.32.0.zip";
      sha256 = "sha256-4I7lSey6I4mQ7dDtuOASnZzAItFYkIDZ8UMsqb0q5tE=";
    };
  };
  deploy-rs = {
    pname = "deploy-rs";
    version = "9c870f63e28ec1e83305f7f6cb73c941e699f74f";
    src = fetchFromGitHub {
      owner = "serokell";
      repo = "deploy-rs";
      rev = "9c870f63e28ec1e83305f7f6cb73c941e699f74f";
      fetchSubmodules = false;
      sha256 = "sha256-9I2H9x5We6Pl+DBYHjR1s3UT8wgwcpAH03kn9CqtdQc=";
    };
    date = "2025-11-04";
  };
  devenv = {
    pname = "devenv";
    version = "v1.10";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "devenv";
      rev = "v1.10";
      fetchSubmodules = false;
      sha256 = "sha256-rsb+6Wca43guzLL4Czoc89L394ZW9JZF2MShxaz2Sx4=";
    };
  };
  dotnet-script = {
    pname = "dotnet-script";
    version = "2.0.0";
    src = fetchTarball {
      url = "https://github.com/dotnet-script/dotnet-script/releases/download/2.0.0/dotnet-script.2.0.0.zip";
      sha256 = "sha256-WMxW6mre1lOCv9mYrtc7+qJf+JXQzmRLAt7iuqA9XiI=";
    };
  };
  doxx = {
    pname = "doxx";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "bgreenwell";
      repo = "doxx";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-V0pBeh9u6iNt6hS1MpUau6nYBdfn9bELhR0GAMqTRmc=";
    };
  };
  font-firacode = {
    pname = "font-firacode";
    version = "6.2";
    src = fetchurl {
      url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip";
      sha256 = "sha256-CUmRW6jrJNif2T0Qp/9iP0KDDXxf/D7L+WDk7K0+Pnk=";
    };
  };
  goctl = {
    pname = "goctl";
    version = "v1.9.3";
    src = fetchFromGitHub {
      owner = "zeromicro";
      repo = "go-zero";
      rev = "v1.9.3";
      fetchSubmodules = false;
      sha256 = "sha256-Q5fRu7EKCPlO6yxEe/GWs4zam7MnomYJn9u0BZqDMy4=";
    };
  };
  kratos = {
    pname = "kratos";
    version = "v2.9.1";
    src = fetchFromGitHub {
      owner = "go-kratos";
      repo = "kratos";
      rev = "v2.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-fgYhrUNivtXNjSGCGCvG35PuKtQ/U5kyC2Irl2h8zXQ=";
    };
  };
  microsoft-edge = {
    pname = "microsoft-edge";
    version = "142.0.3595.53";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_142.0.3595.53-1_amd64.deb";
      sha256 = "sha256-cSSKWxIkQe8jrv7gL5lX2Cs9roU8eD2MIHuLGQMnycM=";
    };
  };
  nix-vscode-extensions = {
    pname = "nix-vscode-extensions";
    version = "3c082362bcec211e14f9b8edf10c2975c74f2d04";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "nix-vscode-extensions";
      rev = "3c082362bcec211e14f9b8edf10c2975c74f2d04";
      fetchSubmodules = false;
      sha256 = "sha256-ctBPb/ea2D+r6Q0Wy0Imakj+YE5rcTTrxOqx4DaEhc0=";
    };
    date = "2025-11-17";
  };
  pwndbg = {
    pname = "pwndbg";
    version = "2025.10.20";
    src = fetchFromGitHub {
      owner = "pwndbg";
      repo = "pwndbg";
      rev = "2025.10.20";
      fetchSubmodules = false;
      sha256 = "sha256-F36ci3+upal+LYW2nK3CrkV86PU05tLIlwJrdADWISY=";
    };
  };
  python = {
    pname = "python";
    version = "100c43175443402084f557154b06f2745995e742";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "nixpkgs-python";
      rev = "100c43175443402084f557154b06f2745995e742";
      fetchSubmodules = false;
      sha256 = "sha256-NEisnXdISmaM5LzX1RatpKR4fa6nlAxkR7QJniFq0vg=";
    };
    date = "2025-11-01";
  };
  shellfirm = {
    pname = "shellfirm";
    version = "v0.2.11";
    src = fetchFromGitHub {
      owner = "kaplanelad";
      repo = "shellfirm";
      rev = "v0.2.11";
      fetchSubmodules = false;
      sha256 = "sha256-jwrH2/EwiB33YoTC+pGO4Jm3tC4dp1DLZLZvhKvUy30=";
    };
  };
  trzsz = {
    pname = "trzsz";
    version = "v1.1.8";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-g1fbgKTFS9aPAmnTeFYoymrDEoZ6BtzUhA2Z9SNYbsU=";
    };
  };
  trzsz-ssh = {
    pname = "trzsz-ssh";
    version = "v0.1.23";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-ssh";
      rev = "v0.1.23";
      fetchSubmodules = false;
      sha256 = "sha256-Cp5XI7ggpt48llojcmarYPi9mTM+YBqwjG/eNAnKTxc=";
    };
  };
  vscode-extension-kotlin-lsp = {
    pname = "vscode-extension-kotlin-lsp";
    version = "0.253.10629";
    src = fetchurl {
      url = "https://download-cdn.jetbrains.com/kotlin-lsp/0.253.10629/kotlin-0.253.10629.vsix";
      name = "kotlin-lsp-0.253.10629.zip";
      sha256 = "sha256-Y47BVS/eflFY+MffBkQ8+5fFwJlXJzeQWGy9WRFb8Rw=";
    };
  };
}
