# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  "1password-cli-linux" = {
    pname = "1password-cli-linux";
    version = "2.34.0";
    src = fetchTarball {
      url = "https://cache.agilebits.com/dist/1P/op2/pkg/v2.34.0/op_linux_amd64_v2.34.0.zip";
      sha256 = "sha256-sbydXPoT0Vo3r2gyZBdl4OMtOejbhvra5JM4wB6Ex5s=";
    };
  };
  cc-switch-cli = {
    pname = "cc-switch-cli";
    version = "5.6.0";
    src = fetchurl {
      url = "https://github.com/SaladDay/cc-switch-cli/releases/download/v5.6.0/cc-switch-cli-v5.6.0-linux-x64-musl.tar.gz";
      sha256 = "sha256-VoECi9EgrObiD5+o6lvjsTfWpM1DFFqtGoi+qF26TLA=";
    };
  };
  codex = {
    pname = "codex";
    version = "0.133.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.133.0/codex-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-0GAZq5w10oG3jcLrsq5VwruX6hG/f0Urr+OQ7dsANO8=";
    };
  };
  deploy-rs = {
    pname = "deploy-rs";
    version = "77c906c0ba56aabdbc72041bf9111b565cdd6171";
    src = fetchFromGitHub {
      owner = "serokell";
      repo = "deploy-rs";
      rev = "77c906c0ba56aabdbc72041bf9111b565cdd6171";
      fetchSubmodules = false;
      sha256 = "sha256-hwsYgDnby50JNVpTRYlF3UR/Rrpt01OrxVuryF40CFY=";
    };
    date = "2026-02-02";
  };
  determinate = {
    pname = "determinate";
    version = "v3.20.0";
    src = fetchFromGitHub {
      owner = "DeterminateSystems";
      repo = "nix-src";
      rev = "v3.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-oyHvP5HDRe59opmjTrq2ED9lh+R9FrHyaCGPPNfBqWM=";
    };
  };
  devenv = {
    pname = "devenv";
    version = "v2.1.2";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "devenv";
      rev = "v2.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-EQnZCy7r4VMO6KDoytxHBa0mFbM1D9g1kaDfs/s0YZA=";
    };
  };
  dotnet-script = {
    pname = "dotnet-script";
    version = "2.0.0";
    src = fetchTarball {
      url = "https://github.com/dotnet-script/dotnet-script/releases/download/2.0.0/dotnet-script.2.0.0.zip";
      sha256 = "sha256-WMxW6mre1lOCv9mYrtc7+qJf+JXQzmRLAt7iuqA9XiI=";
    };
  };
  doxx = {
    pname = "doxx";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "bgreenwell";
      repo = "doxx";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-V0pBeh9u6iNt6hS1MpUau6nYBdfn9bELhR0GAMqTRmc=";
    };
  };
  font-firacode = {
    pname = "font-firacode";
    version = "6.2";
    src = fetchurl {
      url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip";
      sha256 = "sha256-CUmRW6jrJNif2T0Qp/9iP0KDDXxf/D7L+WDk7K0+Pnk=";
    };
  };
  git-hooks-nix = {
    pname = "git-hooks-nix";
    version = "50b9238891e388c9fdc6a5c49e49c42533a1b5ce";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "git-hooks.nix";
      rev = "50b9238891e388c9fdc6a5c49e49c42533a1b5ce";
      fetchSubmodules = false;
      sha256 = "sha256-QlcnByMc8KBjpU37rbq5iP7Cp97HvjRP0ucfdh+M4Qc=";
    };
  };
  goctl = {
    pname = "goctl";
    version = "v1.10.1";
    src = fetchFromGitHub {
      owner = "zeromicro";
      repo = "go-zero";
      rev = "v1.10.1";
      fetchSubmodules = false;
      sha256 = "sha256-oGIhyrz8oodtmjJF48i3DD0N1kLMVXNfMx1mmaBrjGE=";
    };
  };
  hermes-agent = {
    pname = "hermes-agent";
    version = "v2026.5.16";
    src = fetchFromGitHub {
      owner = "NousResearch";
      repo = "hermes-agent";
      rev = "v2026.5.16";
      fetchSubmodules = false;
      sha256 = "sha256-d9qhrTy45Q5UsmjapqMHOVi9e+gR9zE8Nq9Z0wObLmc=";
    };
  };
  kratos = {
    pname = "kratos";
    version = "v2.9.2";
    src = fetchFromGitHub {
      owner = "go-kratos";
      repo = "kratos";
      rev = "v2.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-I2q/4Q2QkJnjnFggfpr8hCK9LKGyGStfXRT1BPVP7bs=";
    };
  };
  microsoft-edge = {
    pname = "microsoft-edge";
    version = "148.0.3967.70";
    src = fetchurl {
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_148.0.3967.70-1_amd64.deb";
      sha256 = "sha256-rwG3zPxMHjC00P591/CZIWRIHb4td4q3Rfz4fvf89k0=";
    };
  };
  opencode = {
    pname = "opencode";
    version = "v1.15.7";
    src = fetchFromGitHub {
      owner = "anomalyco";
      repo = "opencode";
      rev = "v1.15.7";
      fetchSubmodules = false;
      sha256 = "sha256-fk8GDVE+bQfOkZCQ1YEc3V7YIXDHfNC/srcZs/MrE38=";
    };
  };
  opencode-bin = {
    pname = "opencode-bin";
    version = "v1.15.7";
    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v1.15.7/opencode-linux-x64-musl.tar.gz";
      sha256 = "sha256-eWbm8vzeB7g5DVdZ1ddgl/bDuOKhyKR5l3tR5fYBq9s=";
    };
  };
  pwndbg = {
    pname = "pwndbg";
    version = "2026.02.18";
    src = fetchFromGitHub {
      owner = "pwndbg";
      repo = "pwndbg";
      rev = "2026.02.18";
      fetchSubmodules = false;
      sha256 = "sha256-fXceU1vTwNubHeKGjRQnCaB9HR5taXxJotrYp3u0HU4=";
    };
  };
  python = {
    pname = "python";
    version = "a0f88fb785debcb0a201d0ce311a2e3d829e4a1b";
    src = fetchFromGitHub {
      owner = "cachix";
      repo = "nixpkgs-python";
      rev = "a0f88fb785debcb0a201d0ce311a2e3d829e4a1b";
      fetchSubmodules = false;
      sha256 = "sha256-iKhNJH1ABTrPvDF6Sd1U+GCVYSh8Xn88ee10ko7PvvE=";
    };
    date = "2026-05-18";
  };
  shellfirm = {
    pname = "shellfirm";
    version = "v0.3.10";
    src = fetchFromGitHub {
      owner = "kaplanelad";
      repo = "shellfirm";
      rev = "v0.3.10";
      fetchSubmodules = false;
      sha256 = "sha256-nfNK7r+y9KGYb1txHPtUXP7SnipHg94SF3IQhZwZcD0=";
    };
  };
  trzsz = {
    pname = "trzsz";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-CokZAXT61UKSsKnzE5mPMdAZecGX/8mgDkG4yDSat5M=";
    };
  };
  trzsz-ssh = {
    pname = "trzsz-ssh";
    version = "v0.1.25";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-ssh";
      rev = "v0.1.25";
      fetchSubmodules = false;
      sha256 = "sha256-s2WBSEu2A26/VxEFROMGJ5n8piEKgvV2YJZrX8MC9H0=";
    };
  };
}
